### ISSUE TITLE
blockscout cannot catch up transactions.

### ISSUE THREAD

**Issue by scalalang2** [ConsenSys/quorum-kubernetes#118]
When I run blockscout explorer.
it couldn't parse transaction receipt.

Here is the error I get.

```
{:unknown_key, %{key: "isPrivacyMarkerTransaction", value: false}}
80
79
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
78
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
77
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
76
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
75
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
74
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by joshuafernandes** [comment]
Hello @scalalang2 Blockscout isn't a product owned by Consensys. I have [submitted a PR to blockscout to fix this](https://github.com/blockscout/blockscout/pull/5302) - we will update when there is a major release.
