### ISSUE TITLE
Azure cloud-native login module missing?

### ISSUE THREAD

**Issue by HairyMike** [Consensys/quorum-kubernetes#213]
Seems like the login module maybe missing from the init container (used during besu-genesis).  According to the chart, its using image: `repository: consensys/quorum-k8s-hooks:qgt-0.2.12`

```
DEBUG: cli.knack.cli: Command arguments: ['login', '--identity', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f3d8bb092d0>, <function OutputProducer.on_global_arguments at 0x7f3d8b9ffeb0>, <function CLIQuery.on_global_arguments at 0x7f3d8ba4d120>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Command index version or cloud profile is invalid or doesn't match the current command.
DEBUG: cli.azure.cli.core: Command index has been invalidated.
DEBUG: cli.azure.cli.core: No module found from index for '['login', '--identity', '--debug']'
DEBUG: cli.azure.cli.core: Loading all modules and extensions
DEBUG: cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'databoxedge', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'identity', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
```

Subsequently, writing of secrets etc fails:
```
Creating keys in vault for validator-1 ...
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.
configmap/besu-node-validator-1-address created
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.
```
etc

**Comment by HairyMike** [comment]
not so sure that its the module missing.  I had a dig into the dockerfile for the init container, and it does seem to correctly install azure-cli.  There are some more logs that I think may be pertinent to this issue:
```
DEBUG: urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254:80
DEBUG: urllib3.connectionpool: http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 HTTP/1.1" 400 168
DEBUG: msrestazure.azure_active_directory: MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01'}
DEBUG: cli.azure.cli.core.auth.adal_authentication: throw requests.exceptions.HTTPError when doing MSIAuthentication: 
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/adal_authentication.py", line 75, in set_token
    super().set_token()
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 600, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError

DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/adal_authentication.py", line 75, in set_token
    super().set_token()
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 600, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
  File "/opt/az/lib/python3.10/site-packages/msrestazure/azure_active_directory.py", line 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
```

**Comment by HairyMike** [comment]
I've been playing with this a bit more, and it looks like it maybe related to the login method:
https://github.com/Consensys/quorum-kubernetes/blob/master/helm/charts/besu-genesis/templates/genesis-job-init.yaml#L68

If I change this to use an interactive login, everything is great (except its using my credentials to talk to vaults and I need ot manually add access policy etc).

Using `az login --identity` results in this:
```
ERROR: cli.azure.cli.core.azclierror: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned http error: 400, reason: Bad Request
```

**Comment by HairyMike** [comment]
I think I may have gotten to the bottom of the issue.  The resourceGroup needs to be specified in the secret-provider-classes to find the ManagedIdentity in the resource group created by the template.

The reason for this seems to be that the node scaleset for the k8s cluster is created in another resource group.
