### ISSUE TITLE
Error in GenerateBlockchainConfig 

### ISSUE THREAD

**Issue by hugueitor** [ConsenSys/quorum-kubernetes#81]
Hi All,
I'm new in besu development and I am trying to create a private network running on k8s.
As first step I have to create configuration files so I am running:

docker run --rm --volume $PWD/ibftSetup/:/opt/besu/data hyperledger/besu:latest operator generate-blockchain-config --config-file=/opt/besu/data/ibftConfigFile.json --to=/opt/besu/data/networkFiles --private-key-file-name=key

as per indicated in: https://github.com/ConsenSys/quorum-kubernetes/tree/master/helm/quorum-besu/ibft2/besu

Immediately I got this error (I am showing the whole output)

2021-05-28 02:23:07.763+00:00 | main | ERROR | GenerateBlockchainConfig | An error occurred while trying to generate network configuration.
java.nio.file.AccessDeniedException: /opt/besu/data/networkFiles
at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
at java.base/java.nio.file.Files.createDirectory(Unknown Source)
at org.hyperledger.besu.cli.subcommands.operator.GenerateBlockchainConfig.handleOutputDirectory(GenerateBlockchainConfig.java:319)
at org.hyperledger.besu.cli.subcommands.operator.GenerateBlockchainConfig.generateBlockchainConfig(GenerateBlockchainConfig.java:139)
at org.hyperledger.besu.cli.subcommands.operator.GenerateBlockchainConfig.run(GenerateBlockchainConfig.java:125)
at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
at picocli.CommandLine.access$1300(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
at picocli.CommandLine.parseWithHandlers(CommandLine.java:2550)
at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:56)
at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:31)
at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
at picocli.CommandLine.parseWithHandlers(CommandLine.java:2550)
at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1344)
at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1182)
at org.hyperledger.besu.Besu.main(Besu.java:50)

Does somebody have some idea of what is happening?
Your help will be most than appreciated.

**Comment by hugueitor** [comment]
Fixed!, I ran the steps inside the chart's directory structure.
It would be good if the documentation states this,
